### ISSUE TITLE
Put a disclaimer in results modal

### ISSUE THREAD

**Issue by armandasalmd** [armandasalmd/cov-classification-calculator#8]
Copy disclaimer text from footer and put it in the results modal to let the user know its not 100% trustable

**Comment by v1nshul** [comment]
Hello, I will work on this issue :D. Thanks.

**Comment by armandasalmd** [comment]
Can store disclaimer text in utils/constants.js [here](https://github.com/armandasalmd/cov-classification-calculator/blob/production/src/utils/constants.js) - DRY (do not repeat yourself) rule

**Comment by armandasalmd** [comment]
![image](https://user-images.githubusercontent.com/17089888/230773469-9b7da7aa-224a-4b4b-9feb-f0d4c43f094c.png)

This is what is expected view in final code for this issue
